import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from "react"

const inter = Inter({ subsets: ['latin'], display: 'swap', adjustFontFallback: false})


export const metadata: Metadata = {
  title: 'In-Out Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="UTF-8">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
