import type { Metadata } from "next";
import "./globals.css";
import AntdProvider from "@/components/AntdProvider";
import ReduxProvider from "@/components/ReduxProvider";
import NextProvider from "@/components/NextProvider";
import '@/styles/antdOverride.css'
import '@/styles/commonClasses.css'
import '@/styles/layout.css'
import "@/styles/loader.css";
import React from "react";


export const metadata: Metadata = {
  title: "In-Out Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="UTF-8" className='dark'>
      <body className="bg-gray-900 text-white">
        <ReduxProvider>
          <NextProvider>
            <AntdProvider>{children}</AntdProvider>
          </NextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
